// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api_gaurd.proto

package aclpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------- API ENTITY -----------
type Api struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Api) Reset() {
	*x = Api{}
	mi := &file_api_gaurd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Api) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Api) ProtoMessage() {}

func (x *Api) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Api.ProtoReflect.Descriptor instead.
func (*Api) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{0}
}

func (x *Api) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Api) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Api) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type CreateApiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApiRequest) Reset() {
	*x = CreateApiRequest{}
	mi := &file_api_gaurd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiRequest) ProtoMessage() {}

func (x *CreateApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiRequest.ProtoReflect.Descriptor instead.
func (*CreateApiRequest) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{1}
}

func (x *CreateApiRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateApiRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type CreateApiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Api           *Api                   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApiResponse) Reset() {
	*x = CreateApiResponse{}
	mi := &file_api_gaurd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiResponse) ProtoMessage() {}

func (x *CreateApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiResponse.ProtoReflect.Descriptor instead.
func (*CreateApiResponse) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{2}
}

func (x *CreateApiResponse) GetApi() *Api {
	if x != nil {
		return x.Api
	}
	return nil
}

type GetApiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiRequest) Reset() {
	*x = GetApiRequest{}
	mi := &file_api_gaurd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiRequest) ProtoMessage() {}

func (x *GetApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiRequest.ProtoReflect.Descriptor instead.
func (*GetApiRequest) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{3}
}

func (x *GetApiRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetApiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Api           *Api                   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiResponse) Reset() {
	*x = GetApiResponse{}
	mi := &file_api_gaurd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiResponse) ProtoMessage() {}

func (x *GetApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiResponse.ProtoReflect.Descriptor instead.
func (*GetApiResponse) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{4}
}

func (x *GetApiResponse) GetApi() *Api {
	if x != nil {
		return x.Api
	}
	return nil
}

type UpdateApiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApiRequest) Reset() {
	*x = UpdateApiRequest{}
	mi := &file_api_gaurd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApiRequest) ProtoMessage() {}

func (x *UpdateApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApiRequest.ProtoReflect.Descriptor instead.
func (*UpdateApiRequest) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateApiRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateApiRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateApiRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type UpdateApiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Api           *Api                   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApiResponse) Reset() {
	*x = UpdateApiResponse{}
	mi := &file_api_gaurd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApiResponse) ProtoMessage() {}

func (x *UpdateApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApiResponse.ProtoReflect.Descriptor instead.
func (*UpdateApiResponse) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateApiResponse) GetApi() *Api {
	if x != nil {
		return x.Api
	}
	return nil
}

type DeleteApiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApiRequest) Reset() {
	*x = DeleteApiRequest{}
	mi := &file_api_gaurd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApiRequest) ProtoMessage() {}

func (x *DeleteApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApiRequest.ProtoReflect.Descriptor instead.
func (*DeleteApiRequest) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteApiRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteApiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApiResponse) Reset() {
	*x = DeleteApiResponse{}
	mi := &file_api_gaurd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApiResponse) ProtoMessage() {}

func (x *DeleteApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApiResponse.ProtoReflect.Descriptor instead.
func (*DeleteApiResponse) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteApiResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListApisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApisRequest) Reset() {
	*x = ListApisRequest{}
	mi := &file_api_gaurd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApisRequest) ProtoMessage() {}

func (x *ListApisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApisRequest.ProtoReflect.Descriptor instead.
func (*ListApisRequest) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{9}
}

type ListApisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apis          []*Api                 `protobuf:"bytes,1,rep,name=apis,proto3" json:"apis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApisResponse) Reset() {
	*x = ListApisResponse{}
	mi := &file_api_gaurd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApisResponse) ProtoMessage() {}

func (x *ListApisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApisResponse.ProtoReflect.Descriptor instead.
func (*ListApisResponse) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{10}
}

func (x *ListApisResponse) GetApis() []*Api {
	if x != nil {
		return x.Apis
	}
	return nil
}

// ----------- GROUP ENTITY -----------
type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ApiIds        []int64                `protobuf:"varint,3,rep,packed,name=api_ids,json=apiIds,proto3" json:"api_ids,omitempty"` // which APIs the group can access
	ApiKey        string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_api_gaurd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{11}
}

func (x *Group) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetApiIds() []int64 {
	if x != nil {
		return x.ApiIds
	}
	return nil
}

func (x *Group) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ApiIds        []int64                `protobuf:"varint,2,rep,packed,name=api_ids,json=apiIds,proto3" json:"api_ids,omitempty"`
	ApiKey        string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_api_gaurd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{12}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetApiIds() []int64 {
	if x != nil {
		return x.ApiIds
	}
	return nil
}

func (x *CreateGroupRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type CreateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_api_gaurd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{13}
}

func (x *CreateGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_api_gaurd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{14}
}

func (x *GetGroupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResponse) Reset() {
	*x = GetGroupResponse{}
	mi := &file_api_gaurd_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResponse) ProtoMessage() {}

func (x *GetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResponse.ProtoReflect.Descriptor instead.
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{15}
}

func (x *GetGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type UpdateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ApiIds        []string               `protobuf:"bytes,3,rep,name=api_ids,json=apiIds,proto3" json:"api_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_api_gaurd_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateGroupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupRequest) GetApiIds() []string {
	if x != nil {
		return x.ApiIds
	}
	return nil
}

type UpdateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupResponse) Reset() {
	*x = UpdateGroupResponse{}
	mi := &file_api_gaurd_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupResponse) ProtoMessage() {}

func (x *UpdateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type DeleteGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_api_gaurd_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteGroupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupResponse) Reset() {
	*x = DeleteGroupResponse{}
	mi := &file_api_gaurd_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupResponse) ProtoMessage() {}

func (x *DeleteGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_api_gaurd_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{20}
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_api_gaurd_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{21}
}

func (x *ListGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_api_gaurd_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{22}
}

func (x *VerifyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *VerifyRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_api_gaurd_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gaurd_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_api_gaurd_proto_rawDescGZIP(), []int{23}
}

func (x *VerifyResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

var File_api_gaurd_proto protoreflect.FileDescriptor

const file_api_gaurd_proto_rawDesc = "" +
	"\n" +
	"\x0fapi_gaurd.proto\x12\raccesscontrol\x1a\x1cgoogle/api/annotations.proto\"E\n" +
	"\x03Api\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\"B\n" +
	"\x10CreateApiRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\"9\n" +
	"\x11CreateApiResponse\x12$\n" +
	"\x03api\x18\x01 \x01(\v2\x12.accesscontrol.ApiR\x03api\"\x1f\n" +
	"\rGetApiRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x0eGetApiResponse\x12$\n" +
	"\x03api\x18\x01 \x01(\v2\x12.accesscontrol.ApiR\x03api\"R\n" +
	"\x10UpdateApiRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\"9\n" +
	"\x11UpdateApiResponse\x12$\n" +
	"\x03api\x18\x01 \x01(\v2\x12.accesscontrol.ApiR\x03api\"\"\n" +
	"\x10DeleteApiRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x11DeleteApiResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x11\n" +
	"\x0fListApisRequest\":\n" +
	"\x10ListApisResponse\x12&\n" +
	"\x04apis\x18\x01 \x03(\v2\x12.accesscontrol.ApiR\x04apis\"]\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aapi_ids\x18\x03 \x03(\x03R\x06apiIds\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\"Z\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\aapi_ids\x18\x02 \x03(\x03R\x06apiIds\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\"A\n" +
	"\x13CreateGroupResponse\x12*\n" +
	"\x05group\x18\x01 \x01(\v2\x14.accesscontrol.GroupR\x05group\"!\n" +
	"\x0fGetGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\">\n" +
	"\x10GetGroupResponse\x12*\n" +
	"\x05group\x18\x01 \x01(\v2\x14.accesscontrol.GroupR\x05group\"Q\n" +
	"\x12UpdateGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aapi_ids\x18\x03 \x03(\tR\x06apiIds\"A\n" +
	"\x13UpdateGroupResponse\x12*\n" +
	"\x05group\x18\x01 \x01(\v2\x14.accesscontrol.GroupR\x05group\"$\n" +
	"\x12DeleteGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"/\n" +
	"\x13DeleteGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x13\n" +
	"\x11ListGroupsRequest\"B\n" +
	"\x12ListGroupsResponse\x12,\n" +
	"\x06groups\x18\x01 \x03(\v2\x14.accesscontrol.GroupR\x06groups\"D\n" +
	"\rVerifyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\",\n" +
	"\x0eVerifyResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified2\xa4\x03\n" +
	"\x14AccessControlService\x12c\n" +
	"\tCreateApi\x12\x1f.accesscontrol.CreateApiRequest\x1a .accesscontrol.CreateApiResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/apis\x12\\\n" +
	"\x06GetApi\x12\x1c.accesscontrol.GetApiRequest\x1a\x1d.accesscontrol.GetApiResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/apis/{id}\x12k\n" +
	"\vCreateGroup\x12!.accesscontrol.CreateGroupRequest\x1a\".accesscontrol.CreateGroupResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/groups\x12\\\n" +
	"\x06Verify\x12\x1c.accesscontrol.VerifyRequest\x1a\x1d.accesscontrol.VerifyResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/verifyB&Z$github.com/api_gaurd/proto/acl;aclpbb\x06proto3"

var (
	file_api_gaurd_proto_rawDescOnce sync.Once
	file_api_gaurd_proto_rawDescData []byte
)

func file_api_gaurd_proto_rawDescGZIP() []byte {
	file_api_gaurd_proto_rawDescOnce.Do(func() {
		file_api_gaurd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gaurd_proto_rawDesc), len(file_api_gaurd_proto_rawDesc)))
	})
	return file_api_gaurd_proto_rawDescData
}

var file_api_gaurd_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_gaurd_proto_goTypes = []any{
	(*Api)(nil),                 // 0: accesscontrol.Api
	(*CreateApiRequest)(nil),    // 1: accesscontrol.CreateApiRequest
	(*CreateApiResponse)(nil),   // 2: accesscontrol.CreateApiResponse
	(*GetApiRequest)(nil),       // 3: accesscontrol.GetApiRequest
	(*GetApiResponse)(nil),      // 4: accesscontrol.GetApiResponse
	(*UpdateApiRequest)(nil),    // 5: accesscontrol.UpdateApiRequest
	(*UpdateApiResponse)(nil),   // 6: accesscontrol.UpdateApiResponse
	(*DeleteApiRequest)(nil),    // 7: accesscontrol.DeleteApiRequest
	(*DeleteApiResponse)(nil),   // 8: accesscontrol.DeleteApiResponse
	(*ListApisRequest)(nil),     // 9: accesscontrol.ListApisRequest
	(*ListApisResponse)(nil),    // 10: accesscontrol.ListApisResponse
	(*Group)(nil),               // 11: accesscontrol.Group
	(*CreateGroupRequest)(nil),  // 12: accesscontrol.CreateGroupRequest
	(*CreateGroupResponse)(nil), // 13: accesscontrol.CreateGroupResponse
	(*GetGroupRequest)(nil),     // 14: accesscontrol.GetGroupRequest
	(*GetGroupResponse)(nil),    // 15: accesscontrol.GetGroupResponse
	(*UpdateGroupRequest)(nil),  // 16: accesscontrol.UpdateGroupRequest
	(*UpdateGroupResponse)(nil), // 17: accesscontrol.UpdateGroupResponse
	(*DeleteGroupRequest)(nil),  // 18: accesscontrol.DeleteGroupRequest
	(*DeleteGroupResponse)(nil), // 19: accesscontrol.DeleteGroupResponse
	(*ListGroupsRequest)(nil),   // 20: accesscontrol.ListGroupsRequest
	(*ListGroupsResponse)(nil),  // 21: accesscontrol.ListGroupsResponse
	(*VerifyRequest)(nil),       // 22: accesscontrol.VerifyRequest
	(*VerifyResponse)(nil),      // 23: accesscontrol.VerifyResponse
}
var file_api_gaurd_proto_depIdxs = []int32{
	0,  // 0: accesscontrol.CreateApiResponse.api:type_name -> accesscontrol.Api
	0,  // 1: accesscontrol.GetApiResponse.api:type_name -> accesscontrol.Api
	0,  // 2: accesscontrol.UpdateApiResponse.api:type_name -> accesscontrol.Api
	0,  // 3: accesscontrol.ListApisResponse.apis:type_name -> accesscontrol.Api
	11, // 4: accesscontrol.CreateGroupResponse.group:type_name -> accesscontrol.Group
	11, // 5: accesscontrol.GetGroupResponse.group:type_name -> accesscontrol.Group
	11, // 6: accesscontrol.UpdateGroupResponse.group:type_name -> accesscontrol.Group
	11, // 7: accesscontrol.ListGroupsResponse.groups:type_name -> accesscontrol.Group
	1,  // 8: accesscontrol.AccessControlService.CreateApi:input_type -> accesscontrol.CreateApiRequest
	3,  // 9: accesscontrol.AccessControlService.GetApi:input_type -> accesscontrol.GetApiRequest
	12, // 10: accesscontrol.AccessControlService.CreateGroup:input_type -> accesscontrol.CreateGroupRequest
	22, // 11: accesscontrol.AccessControlService.Verify:input_type -> accesscontrol.VerifyRequest
	2,  // 12: accesscontrol.AccessControlService.CreateApi:output_type -> accesscontrol.CreateApiResponse
	4,  // 13: accesscontrol.AccessControlService.GetApi:output_type -> accesscontrol.GetApiResponse
	13, // 14: accesscontrol.AccessControlService.CreateGroup:output_type -> accesscontrol.CreateGroupResponse
	23, // 15: accesscontrol.AccessControlService.Verify:output_type -> accesscontrol.VerifyResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_gaurd_proto_init() }
func file_api_gaurd_proto_init() {
	if File_api_gaurd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gaurd_proto_rawDesc), len(file_api_gaurd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gaurd_proto_goTypes,
		DependencyIndexes: file_api_gaurd_proto_depIdxs,
		MessageInfos:      file_api_gaurd_proto_msgTypes,
	}.Build()
	File_api_gaurd_proto = out.File
	file_api_gaurd_proto_goTypes = nil
	file_api_gaurd_proto_depIdxs = nil
}
